### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by milkasir** [KoishiStudio/nonebot-plugin-giyf#2]
config_manager.py line30和line85的removeprefix是py3.9特性，3.9以下会报AttributeError: 'str' object has no attribute 'removeprefix'，我试了下改成lstrip就能用，但是全局指令.gobal就不识别了。

**Comment by KoishiMoe** [comment]
这样啊，我没在3.9以下的环境测过，pycharm说没问题我就当没问题了😂；一会去修

**Comment by KoishiMoe** [comment]
最新版本应该可以用了，如果还有问题的话，请重开此issue
